/**
 * MotionPlay active-play catalogue.
 *
 * The public catalogue is intentionally product-led: children pick an
 * experience, while the motion engine underneath records the physical actions
 * performed during the round. Some entries currently reuse a proven Stage 0
 * engine while their dedicated visuals/mechanics are being built. `artId`
 * keeps the matching Stage 0 card artwork during that transition.
 *
 * `skills` describe the movement focus used for browsing. `actions` are the
 * countable motions stored in the activity history. `benefits` are safe,
 * non-medical activity-focus labels resolved by ../wellness.js.
 */
export const GAMES = [
  {
    id: "motion-runner",
    artId: "jump-the-wall",
    skills: ["lower-body", "agility", "reaction"],
    actions: ["jump", "duck"],
    benefits: ["active-play", "lower-body", "reaction", "motor-planning"],
    title: "Motion Runner",
    tagline: "Run, jump and duck through the adventure",
    needs: "full",
    backdrop: "scene",
    orientation: "landscape",
    accent: "#f97316",
    howTo: ["Jump to clear obstacles", "Crouch to pass under barriers"],
    ready: true,
    load: () => import("./jump-the-wall.js"),
  },
  {
    id: "fruit-slice",
    artId: "fruit-slice",
    skills: ["coordination", "upper-body", "reaction"],
    actions: ["swipe"],
    benefits: ["active-play", "coordination", "upper-body", "cross-body", "reaction"],
    title: "Fruit Slice",
    tagline: "Slice flying fruit with real arm swipes",
    needs: "upper",
    backdrop: "camera",
    accent: "#22c55e",
    howTo: ["Swing a whole arm through the fruit", "Stay quick and avoid the bombs"],
    ready: true,
    load: () => import("./fruit-slice.js"),
  },
  {
    id: "kart-racer",
    artId: "ski-slalom",
    skills: ["balance", "core", "agility"],
    actions: ["lean"],
    benefits: ["active-play", "balance", "postural-control", "reaction"],
    title: "Kart Racer",
    tagline: "Lean your body to steer through the course",
    needs: "full",
    backdrop: "scene",
    accent: "#38bdf8",
    leanFor: "gates",
    howTo: ["Lean left or right to steer", "Return to centre to straighten up"],
    ready: true,
    load: () => import("./ski-slalom.js"),
  },
  {
    id: "goalkeeper-hero",
    artId: "goalkeeper",
    skills: ["reach", "reaction", "coordination"],
    actions: ["reach"],
    benefits: ["active-play", "coordination", "upper-body", "reaction", "mobility"],
    title: "Goalkeeper Hero",
    tagline: "Reach high and low to save every shot",
    needs: "upper",
    backdrop: "camera",
    accent: "#6366f1",
    reachFor: "ball",
    howTo: ["Reach either hand towards the ball", "React quickly to high and low shots"],
    ready: true,
    load: () => import("./goalkeeper.js"),
  },
  {
    id: "boxing-challenge",
    artId: "punch-out",
    skills: ["upper-body", "reaction", "coordination"],
    actions: ["punch"],
    benefits: ["active-play", "coordination", "upper-body", "reaction"],
    title: "Boxing Challenge",
    tagline: "Punch the glowing targets on cue",
    needs: "upper",
    backdrop: "camera",
    accent: "#ef4444",
    howTo: ["Punch the pad that lights up", "Pull your hand back before the next punch"],
    ready: true,
    load: () => import("./punch-out.js"),
  },
  {
    id: "dance-copycat",
    artId: "pose-match",
    skills: ["posture", "balance", "coordination"],
    actions: ["hold"],
    benefits: ["active-play", "coordination", "balance", "postural-control", "motor-planning"],
    title: "Dance Copycat",
    tagline: "Copy the pose and hold it like a dance star",
    needs: "full",
    backdrop: "camera",
    accent: "#eab308",
    howTo: ["Copy the body shape on screen", "Hold the pose until it locks in"],
    ready: true,
    load: () => import("./pose-match.js"),
  },
  {
    id: "jump-island",
    artId: "squat-rush",
    skills: ["lower-body", "core", "agility"],
    actions: ["squat"],
    benefits: ["active-play", "lower-body", "postural-control"],
    title: "Jump Island",
    tagline: "Power up the island with deep up-and-down moves",
    needs: "full",
    backdrop: "scene",
    accent: "#a855f7",
    howTo: ["Drop into a controlled squat", "Stand tall to charge the next island"],
    ready: true,
    load: () => import("./squat-rush.js"),
  },
  {
    id: "balloon-pop-adventure",
    artId: "balloon-pop",
    skills: ["reach", "coordination", "upper-body"],
    actions: ["reach"],
    benefits: ["active-play", "coordination", "upper-body", "mobility", "cross-body"],
    title: "Balloon Pop Adventure",
    tagline: "Reach around the screen before balloons escape",
    needs: "upper",
    backdrop: "camera",
    accent: "#ec4899",
    howTo: ["Reach out and touch a balloon", "Use both sides of your body"],
    ready: true,
    load: () => import("./balloon-pop.js"),
  },
  {
    id: "ninja-dodge",
    artId: "lane-runner",
    skills: ["balance", "core", "reaction"],
    actions: ["lean"],
    benefits: ["active-play", "balance", "reaction", "motor-planning"],
    title: "Ninja Dodge",
    tagline: "Shift left and right to escape the hazards",
    needs: "full",
    backdrop: "scene",
    accent: "#0ea5e9",
    howTo: ["Lean left or right to change lane", "Return to the middle before the next hazard"],
    ready: true,
    load: () => import("./lane-runner.js"),
  },
  {
    id: "animal-adventure",
    artId: "body-drums",
    skills: ["coordination", "lower-body", "reaction"],
    actions: ["punch", "kick"],
    benefits: ["active-play", "coordination", "lower-body", "upper-body", "reaction"],
    title: "Animal Adventure",
    tagline: "Use paws and knee drives to follow the rhythm",
    needs: "full",
    backdrop: "camera",
    accent: "#fbbf24",
    howTo: ["Strike high targets with your hands", "Drive your knees into the low targets on the beat"],
    ready: true,
    load: () => import("./body-drums.js"),
  },
  {
    id: "space-defender",
    artId: "sky-flap",
    skills: ["upper-body", "coordination", "reaction"],
    actions: ["raise"],
    benefits: ["active-play", "upper-body", "coordination", "mobility"],
    title: "Space Defender",
    tagline: "Raise and lower your arms to fly through space",
    needs: "upper",
    backdrop: "scene",
    accent: "#14b8a6",
    howTo: ["Raise both hands to move up", "Lower your hands to move down"],
    ready: true,
    load: () => import("./sky-flap.js"),
  },
  {
    id: "treasure-catch",
    artId: "orbit-keeper",
    skills: ["coordination", "reaction", "balance"],
    actions: ["reach", "kick"],
    benefits: ["active-play", "coordination", "reaction", "upper-body", "lower-body"],
    title: "Treasure Catch",
    tagline: "Use arms and legs to keep treasures in play",
    needs: "full",
    backdrop: "camera",
    accent: "#38bdf8",
    reachFor: "orbit",
    howTo: ["Use your arms and legs to tap the treasures", "Guide them into the moving chest"],
    ready: true,
    load: () => import("./orbit-keeper.js"),
  },
  {
    id: "balance-bridge",
    artId: "ski-slalom",
    skills: ["balance", "core", "posture"],
    actions: ["lean"],
    benefits: ["active-play", "balance", "postural-control"],
    title: "Balance Bridge",
    tagline: "Control your weight shift and stay on the path",
    needs: "full",
    backdrop: "scene",
    accent: "#0f9b8e",
    leanFor: "gates",
    howTo: ["Lean gently towards the safe side", "Come back to centre under control"],
    ready: true,
    load: () => import("./ski-slalom.js"),
  },
  {
    id: "adventure-climber",
    artId: "hand-tetris",
    skills: ["coordination", "reach", "upper-body"],
    actions: ["reach", "raise"],
    benefits: ["active-play", "coordination", "upper-body", "mobility", "motor-planning"],
    title: "Adventure Climber",
    tagline: "Reach, lift and guide your way up",
    needs: "upper",
    backdrop: "camera",
    accent: "#60a5fa",
    reachFor: "block",
    raiseFor: "turn",
    howTo: ["Sweep a hand across to guide the next step", "Raise a hand above your shoulder to change direction"],
    ready: true,
    load: () => import("./hand-tetris.js"),
  },
  {
    id: "simon-says-motion",
    artId: "freeze-frame",
    skills: ["posture", "reaction", "core"],
    actions: ["hold"],
    benefits: ["active-play", "reaction", "postural-control", "motor-planning"],
    title: "Simon Says Motion",
    tagline: "Move on the cue and freeze when Simon says stop",
    needs: "full",
    backdrop: "camera",
    accent: "#ef4444",
    holdFor: "freeze",
    howTo: ["Move while the cue is green", "Freeze as soon as the cue turns red"],
    ready: true,
    load: () => import("./freeze-frame.js"),
  },
];

export const gameById = (id) => GAMES.find((g) => g.id === id) ?? null;
